### ISSUE TITLE
Incorrect output for HOWTO getNumberOfOccurrencesForLetter

### ISSUE THREAD

**Issue by AndreasHassing** [andry-tino/ws-crypto-histo#13]
I've got a baaaad feeling about this:
![image](https://user-images.githubusercontent.com/639843/45823746-addd4d00-bcee-11e8-9adc-f156e08bc3f8.png)

https://github.com/andry-tino/ws-crypto-histo/blob/master/output/HOWTO.md#function-getnumberofoccurrencesforletter

**Comment by andry-tino** [comment]
It works for me... Are you sure you are executing it right? If you are using the online link, wait for that, it is not updated, but the latest release it is ok.

**Comment by AndreasHassing** [comment]
@andry-tino: I was referring to the output generated by the script, you've written that the output is `e` 🙂.

**Comment by AndreasHassing** [comment]
Seems to be fixed now. Closing!
